# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
  configuration: docs/conf.py

formats:
  - htmlzip

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    pre_create_environment:
      # Install uv
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    create_environment:
      # Create virtual environment with uv
      - uv venv $READTHEDOCS_VIRTUALENV_PATH
    install:
      # Install jax-md and doc dependencies with uv
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --group docs
    pre_build:
      - cp -r examples docs/
      - uv run jupytext --to notebook docs/examples/*.py
      - uv run jupytext --to notebook docs/examples/units/*.py
      - rm docs/examples/*.py
      - rm docs/examples/units/*.py
    post_build:
      - mkdir -p $READTHEDOCS_OUTPUT/html/notebooks
      - mkdir -p $READTHEDOCS_OUTPUT/html/notebooks/units
      - cp docs/examples/*.ipynb $READTHEDOCS_OUTPUT/html/notebooks/
      - cp docs/examples/units/*.ipynb $READTHEDOCS_OUTPUT/html/notebooks/units/
