# Ruff configuration
exclude = [
    "examples",
    "notebooks",
]

[lint]
ignore = [
    "E731",  # Do not assign a lambda expression, use a def
    "E741",  # Ambiguous variable name
    "F811",  # Redefinition of unused name
    "F841",  # Local variable is assigned to but never used
    "F401",
]
